### ISSUE TITLE
how to get sleep data using core motion do you have any idea?

### ISSUE THREAD

**Issue by SagarDabhi** [cansurmeli/pedestrian-status#4]

**Comment by cansurmeli** [comment]
Hello.

Although I've looked extensively into accelerometer usage in terms of motion tracking, I've never dealt with sleep state tracking.

Besides using Google Scholar or ResearchGate to find researches regarding this manner, if you want to explore this yourself, just build a basic accelerometer data retrieving/displaying app and see what happens when you sleep. 😉

Have fun!

**Comment by SagarDabhi** [comment]
@cansurmeli  Thanks for you response, Now able to get sleep using CMMotionActivityManager, it will not give direct sleep count for that we have to use own algo.
